name: Unity Multi-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Unity (${{ matrix.targetPlatform }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [WebGL, StandaloneWindows64, StandaloneOSX]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Active la licence étudiant Unity
      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 6000.2.0f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

      # Build
      - name: Build for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 6000.2.0f1

      # Sauvegarde du build en artifact téléchargeable
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      # Libère la licence Unity 
      - name: Return License
        if: always()
        uses: game-ci/unity-return-license@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
